/**
 * Generates the row-level security migration from the schema.
 *
 *   node scripts/gen-rls.mjs --modules <dir> [--out drizzle/0001_rls.sql]
 *
 * Every table that carries a `tenant_id` gets `ENABLE` + **`FORCE`** row level security and
 * a `tenant_isolation` policy, plus the grants the application role needs. Generating it
 * means a new table cannot be left unprotected by forgetting a migration line — the same
 * reason the isolation suite walks the schema instead of reading a list (§13.2).
 *
 * Re-run it after adding a tenant-scoped table, review the diff, and commit it.
 *
 * P2.12: a table created by a *later* migration cannot be covered by 0001 — 0001 runs before
 * the table exists, and its `ON ALL TABLES` grant only reaches tables that existed then. Such a
 * table gets its block written into the migration that creates it, between `-- rls:begin` and
 * `-- rls:end` (inserted before `-- ROLLBACK:` the first time, replaced after). The block is
 * the same policy and grants 0001 would have written, plus the admin role's grant. The
 * table's own `DROP TABLE` in the rollback removes all of it.
 */
import { createRequire } from 'node:module';
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const arg = (name, fallback) => {
  const i = process.argv.indexOf(name);
  return i > -1 ? process.argv[i + 1] : fallback;
};
const MODULES = path.resolve(arg('--modules', path.join(ROOT, 'node_modules')));
const OUT = path.resolve(ROOT, arg('--out', 'drizzle/0001_rls.sql'));
const BREAK = '\n--> statement-breakpoint\n';

const require = createRequire(path.join(MODULES, '_.js'));
const esbuild = require('esbuild');

// Bundle a tiny entry that prints the table names, so this script never has to parse TS.
const schemaPath = path.join(ROOT, 'db/schema/index.ts').split(path.sep).join('/');
const entry = path.join(MODULES, '..', '.rls-entry.mjs');
fs.writeFileSync(entry, [
  `import { ALL_TABLES, APPEND_ONLY, EXEMPT, RLS_EXEMPT, tableName, tenantColumnOf } from '${schemaPath}';`,
  'const withTenantColumn = ALL_TABLES.filter((t) => tenantColumnOf(t) !== null).map(tableName);',
  'const scoped = withTenantColumn.filter((n) => !RLS_EXEMPT[n]).sort();',
  'const noTenantColumn = ALL_TABLES.map(tableName).filter((n) => !withTenantColumn.includes(n)).sort();',
  'console.log(JSON.stringify({',
  '  scoped,',
  '  noTenantColumn,',
  '  documented: Object.keys(EXEMPT).sort(),',
  '  rlsExempt: Object.keys(RLS_EXEMPT).sort(),',
  '  appendOnly: Object.keys(APPEND_ONLY).sort(),',
  '}));',
].join('\n'));

const bundle = path.join(MODULES, '..', '.rls-bundle.cjs');
await esbuild.build({
  entryPoints: [entry],
  outfile: bundle,
  bundle: true,
  platform: 'node',
  format: 'cjs',
  target: 'node20',
  nodePaths: [MODULES],
  logLevel: 'warning',
});

const raw = execFileSync(process.execPath, [bundle], { encoding: 'utf8' });
const { scoped, noTenantColumn, documented, rlsExempt, appendOnly } = JSON.parse(raw.trim().split('\n').pop());
fs.rmSync(entry, { force: true });
fs.rmSync(bundle, { force: true });

// Which migration creates each schema table: 0001 covers those 0000_init creates; later ones
// carry their own block.
const MIGRATIONS = path.join(ROOT, 'drizzle');
const createdIn = new Map();
for (const file of fs.readdirSync(MIGRATIONS).filter((f) => f.endsWith('.sql')).sort()) {
  const forward = fs.readFileSync(path.join(MIGRATIONS, file), 'utf8').split('-- ROLLBACK:')[0];
  for (const [, name] of forward.matchAll(/CREATE TABLE (?:IF NOT EXISTS )?"?([a-z_0-9]+)"?/gi)) {
    if (!createdIn.has(name)) createdIn.set(name, file);
  }
}
const early = (name) => createdIn.get(name) === '0000_init.sql' || !createdIn.has(name);

const undocumented = noTenantColumn.filter((name) => name !== 'tenants' && !documented.includes(name));
if (undocumented.length) {
  console.error(`No tenant column and no EXEMPT entry: ${undocumented.join(', ')}`);
  process.exit(1);
}

const header = `-- Row-level security (§7.1). GENERATED by scripts/gen-rls.mjs — do not hand-edit.
--
-- ${scoped.filter(early).length} tables get a policy. The two lists at the bottom are the tables that do
-- not, each with the reason recorded in db/schema/index.ts.
--
-- Two roles, both NOLOGIN here and granted to real login roles by the deployment:
--   tajribah_app    merchant requests. Neither owner nor superuser, so the policies apply.
--   tajribah_admin  BYPASSRLS, for the work that precedes or spans a tenant — registration,
--                   login's membership lookup, the job queue. Every query it runs filters
--                   by tenant explicitly; wrapping it in withTenant scopes nothing (§13.2).
`;

const preamble = `
CREATE ROLE tajribah_app NOLOGIN;${BREAK}
CREATE ROLE tajribah_admin NOLOGIN BYPASSRLS;${BREAK}
-- NULLIF, not an inline cast: COMMIT resets a transaction-local GUC to the empty string,
-- and ''::uuid raises instead of returning no rows (§13.1). Fail closed, quietly.
CREATE FUNCTION current_tenant_id() RETURNS uuid LANGUAGE sql STABLE AS $$
  SELECT NULLIF(current_setting('app.tenant_id', true), '')::uuid
$$;${BREAK}
GRANT USAGE ON SCHEMA public TO tajribah_app;${BREAK}
GRANT EXECUTE ON FUNCTION current_tenant_id() TO tajribah_app;${BREAK}
GRANT USAGE ON SCHEMA public TO tajribah_admin;${BREAK}
GRANT EXECUTE ON FUNCTION current_tenant_id() TO tajribah_admin;${BREAK}
-- Explicit DML on every table, including the read-only catalogues: migrations own the schema,
-- the admin role only reads and writes rows.
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO tajribah_admin;`;

const policyOf = (name) => [
  `ALTER TABLE "${name}" ENABLE ROW LEVEL SECURITY;`,
  `ALTER TABLE "${name}" FORCE ROW LEVEL SECURITY;`,
  `CREATE POLICY tenant_isolation ON "${name}"`,
  '  USING (tenant_id = current_tenant_id())',
  '  WITH CHECK (tenant_id = current_tenant_id());',
  // Append-only tables (APPEND_ONLY in db/schema/index.ts): the app may add and read, never
  // rewrite. The admin role keeps full DML for erasure and retention.
  appendOnly.includes(name)
    ? `GRANT SELECT, INSERT ON "${name}" TO tajribah_app;`
    : `GRANT SELECT, INSERT, UPDATE, DELETE ON "${name}" TO tajribah_app;`,
].join('\n');
const policies = scoped.filter(early).map(policyOf).join(BREAK);

// Platform catalogues are readable by the app and writable only by migrations. GRANT SELECT
// does not make a table read-only on its own — the REVOKE has to come first (§13.2).
const READ_ONLY_CATALOGUES = ['plans', 'plan_limits', 'plan_features', 'model_registry', 'coupons', 'announcements'];
const readOnlyOf = (name) => [
  `REVOKE ALL ON "${name}" FROM tajribah_app;`,
  `GRANT SELECT ON "${name}" TO tajribah_app;`,
].join('\n');
const readOnly = READ_ONLY_CATALOGUES
  .filter((name) => noTenantColumn.includes(name) && early(name))
  .map(readOnlyOf).join(BREAK);

// Platform infrastructure: a tenant column, deliberately no policy (RLS_EXEMPT).
const infrastructure = rlsExempt.filter(early)
  .map((name) => `GRANT SELECT, INSERT, UPDATE, DELETE ON "${name}" TO tajribah_app;`)
  .join(BREAK);

const GLOBALS = ['users', 'tenants', 'verification_tokens', 'billing_events'];
const globals = GLOBALS
  .filter((name) => noTenantColumn.includes(name) && early(name))
  .map((name) => `GRANT SELECT, INSERT, UPDATE, DELETE ON "${name}" TO tajribah_app;`)
  .join(BREAK);

const rollback = [
  ...scoped.filter(early).flatMap((name) => [
    `DROP POLICY IF EXISTS tenant_isolation ON "${name}";`,
    `ALTER TABLE "${name}" NO FORCE ROW LEVEL SECURITY;`,
    `ALTER TABLE "${name}" DISABLE ROW LEVEL SECURITY;`,
  ]),
  'REVOKE ALL ON ALL TABLES IN SCHEMA public FROM tajribah_app, tajribah_admin;',
  'REVOKE ALL ON SCHEMA public FROM tajribah_app, tajribah_admin;',
  'DROP FUNCTION IF EXISTS current_tenant_id();',
  'DROP ROLE IF EXISTS tajribah_admin;',
  'DROP ROLE IF EXISTS tajribah_app;',
];

const footer = `
-- No tenant column (EXEMPT):
${noTenantColumn.filter(early).map((name) => `--   ${name}`).join('\n')}
--
-- Tenant column, no policy (RLS_EXEMPT):
${rlsExempt.filter(early).map((name) => `--   ${name}`).join('\n')}

-- ROLLBACK:
-- Executable as written once the leading "-- " is removed; the migration test runs it.
-- Grants are revoked before the roles are dropped: a role that still holds privileges
-- cannot be dropped.
${rollback.map((line) => `-- ${line}`).join('\n')}
`;

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, [
  header, preamble, BREAK, policies, BREAK, readOnly, BREAK, infrastructure, BREAK, globals, footer,
].join('\n'));

// Tables created by later migrations: each migration carries its own generated block.
const later = new Map();
for (const name of [...scoped, ...rlsExempt, ...noTenantColumn]) {
  if (early(name)) continue;
  const file = createdIn.get(name);
  const lines = [];
  if (scoped.includes(name)) lines.push(policyOf(name));
  else if (rlsExempt.includes(name)) lines.push(`GRANT SELECT, INSERT, UPDATE, DELETE ON "${name}" TO tajribah_app;`);
  else if (READ_ONLY_CATALOGUES.includes(name)) lines.push(readOnlyOf(name));
  else if (GLOBALS.includes(name)) lines.push(`GRANT SELECT, INSERT, UPDATE, DELETE ON "${name}" TO tajribah_app;`);
  else lines.push(`-- "${name}": no tenant column and no app grant — admin role only (EXEMPT).`);
  // 0001's ON ALL TABLES grant never reached this table.
  lines.push(`GRANT SELECT, INSERT, UPDATE, DELETE ON "${name}" TO tajribah_admin;`);
  later.set(file, [...(later.get(file) ?? []), lines.join('\n')]);
}
const BEGIN = '-- rls:begin — GENERATED by scripts/gen-rls.mjs from db/schema; do not hand-edit';
const END = '-- rls:end';
for (const [file, blocks] of later) {
  const target = path.join(MIGRATIONS, file);
  const text = fs.readFileSync(target, 'utf8');
  const block = `${BEGIN}${BREAK}${blocks.join(BREAK)}\n${END}`;
  const start = text.indexOf('-- rls:begin');
  let next;
  if (start >= 0) {
    const stop = text.indexOf(END, start) + END.length;
    next = text.slice(0, start) + block + text.slice(stop);
  } else {
    const at = text.indexOf('-- ROLLBACK:');
    if (at < 0) { console.error(`${file} creates a table but has no -- ROLLBACK: block`); process.exit(1); }
    next = `${text.slice(0, at)}--> statement-breakpoint\n${block}\n\n${text.slice(at)}`;
  }
  if (next !== text) fs.writeFileSync(target, next);
  console.log(`wrote the RLS block into drizzle/${file} (${blocks.length} table${blocks.length > 1 ? 's' : ''})`);
}

console.log(
  `wrote ${path.relative(ROOT, OUT)} — ${scoped.filter(early).length} with a policy, ` +
  `${rlsExempt.filter(early).length} infrastructure, ${noTenantColumn.filter(early).length} without a tenant column`,
);
