-- Row-level security (§7.1). GENERATED by scripts/gen-rls.mjs — do not hand-edit.
--
-- 39 tables get a policy. The two lists at the bottom are the tables that do
-- not, each with the reason recorded in db/schema/index.ts.
--
-- Two roles, both NOLOGIN here and granted to real login roles by the deployment:
--   tajribah_app    merchant requests. Neither owner nor superuser, so the policies apply.
--   tajribah_admin  BYPASSRLS, for the work that precedes or spans a tenant — registration,
--                   login's membership lookup, the job queue. Every query it runs filters
--                   by tenant explicitly; wrapping it in withTenant scopes nothing (§13.2).


CREATE ROLE tajribah_app NOLOGIN;
--> statement-breakpoint

CREATE ROLE tajribah_admin NOLOGIN BYPASSRLS;
--> statement-breakpoint

-- NULLIF, not an inline cast: COMMIT resets a transaction-local GUC to the empty string,
-- and ''::uuid raises instead of returning no rows (§13.1). Fail closed, quietly.
CREATE FUNCTION current_tenant_id() RETURNS uuid LANGUAGE sql STABLE AS $$
  SELECT NULLIF(current_setting('app.tenant_id', true), '')::uuid
$$;
--> statement-breakpoint

GRANT USAGE ON SCHEMA public TO tajribah_app;
--> statement-breakpoint

GRANT EXECUTE ON FUNCTION current_tenant_id() TO tajribah_app;
--> statement-breakpoint

GRANT USAGE ON SCHEMA public TO tajribah_admin;
--> statement-breakpoint

GRANT EXECUTE ON FUNCTION current_tenant_id() TO tajribah_admin;
--> statement-breakpoint

-- Explicit DML on every table, including the read-only catalogues: migrations own the schema,
-- the admin role only reads and writes rows.
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO tajribah_admin;

--> statement-breakpoint

ALTER TABLE "ai_job_events" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ai_job_events" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "ai_job_events"
  USING (tenant_id = current_tenant_id())
  WITH CHECK (tenant_id = current_tenant_id());
GRANT SELECT, INSERT, UPDATE, DELETE ON "ai_job_events" TO tajribah_app;
--> statement-breakpoint
ALTER TABLE "ai_jobs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ai_jobs" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "ai_jobs"
  USING (tenant_id = current_tenant_id())
  WITH CHECK (tenant_id = current_tenant_id());
GRANT SELECT, INSERT, UPDATE, DELETE ON "ai_jobs" TO tajribah_app;
--> statement-breakpoint
ALTER TABLE "analytics_events" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "analytics_events" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "analytics_events"
  USING (tenant_id = current_tenant_id())
  WITH CHECK (tenant_id = current_tenant_id());
GRANT SELECT, INSERT, UPDATE, DELETE ON "analytics_events" TO tajribah_app;
--> statement-breakpoint
ALTER TABLE "api_keys" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "api_keys" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "api_keys"
  USING (tenant_id = current_tenant_id())
  WITH CHECK (tenant_id = current_tenant_id());
GRANT SELECT, INSERT, UPDATE, DELETE ON "api_keys" TO tajribah_app;
--> statement-breakpoint
ALTER TABLE "ar_configs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ar_configs" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "ar_configs"
  USING (tenant_id = current_tenant_id())
  WITH CHECK (tenant_id = current_tenant_id());
GRANT SELECT, INSERT, UPDATE, DELETE ON "ar_configs" TO tajribah_app;
--> statement-breakpoint
ALTER TABLE "audit_logs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "audit_logs" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "audit_logs"
  USING (tenant_id = current_tenant_id())
  WITH CHECK (tenant_id = current_tenant_id());
GRANT SELECT, INSERT ON "audit_logs" TO tajribah_app;
--> statement-breakpoint
ALTER TABLE "categories" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "categories" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "categories"
  USING (tenant_id = current_tenant_id())
  WITH CHECK (tenant_id = current_tenant_id());
GRANT SELECT, INSERT, UPDATE, DELETE ON "categories" TO tajribah_app;
--> statement-breakpoint
ALTER TABLE "conversion_daily" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "conversion_daily" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "conversion_daily"
  USING (tenant_id = current_tenant_id())
  WITH CHECK (tenant_id = current_tenant_id());
GRANT SELECT, INSERT, UPDATE, DELETE ON "conversion_daily" TO tajribah_app;
--> statement-breakpoint
ALTER TABLE "credit_ledger" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "credit_ledger" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "credit_ledger"
  USING (tenant_id = current_tenant_id())
  WITH CHECK (tenant_id = current_tenant_id());
GRANT SELECT, INSERT, UPDATE, DELETE ON "credit_ledger" TO tajribah_app;
--> statement-breakpoint
ALTER TABLE "daily_product_stats" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "daily_product_stats" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "daily_product_stats"
  USING (tenant_id = current_tenant_id())
  WITH CHECK (tenant_id = current_tenant_id());
GRANT SELECT, INSERT, UPDATE, DELETE ON "daily_product_stats" TO tajribah_app;
--> statement-breakpoint
ALTER TABLE "daily_tenant_stats" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "daily_tenant_stats" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "daily_tenant_stats"
  USING (tenant_id = current_tenant_id())
  WITH CHECK (tenant_id = current_tenant_id());
GRANT SELECT, INSERT, UPDATE, DELETE ON "daily_tenant_stats" TO tajribah_app;
--> statement-breakpoint
ALTER TABLE "data_requests" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "data_requests" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "data_requests"
  USING (tenant_id = current_tenant_id())
  WITH CHECK (tenant_id = current_tenant_id());
GRANT SELECT, INSERT, UPDATE, DELETE ON "data_requests" TO tajribah_app;
--> statement-breakpoint
ALTER TABLE "device_breakdown_daily" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "device_breakdown_daily" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "device_breakdown_daily"
  USING (tenant_id = current_tenant_id())
  WITH CHECK (tenant_id = current_tenant_id());
GRANT SELECT, INSERT, UPDATE, DELETE ON "device_breakdown_daily" TO tajribah_app;
--> statement-breakpoint
ALTER TABLE "field_mappings" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "field_mappings" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "field_mappings"
  USING (tenant_id = current_tenant_id())
  WITH CHECK (tenant_id = current_tenant_id());
GRANT SELECT, INSERT, UPDATE, DELETE ON "field_mappings" TO tajribah_app;
--> statement-breakpoint
ALTER TABLE "generation_inputs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "generation_inputs" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "generation_inputs"
  USING (tenant_id = current_tenant_id())
  WITH CHECK (tenant_id = current_tenant_id());
GRANT SELECT, INSERT, UPDATE, DELETE ON "generation_inputs" TO tajribah_app;
--> statement-breakpoint
ALTER TABLE "hosted_pages" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "hosted_pages" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "hosted_pages"
  USING (tenant_id = current_tenant_id())
  WITH CHECK (tenant_id = current_tenant_id());
GRANT SELECT, INSERT, UPDATE, DELETE ON "hosted_pages" TO tajribah_app;
--> statement-breakpoint
ALTER TABLE "invitations" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "invitations" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "invitations"
  USING (tenant_id = current_tenant_id())
  WITH CHECK (tenant_id = current_tenant_id());
GRANT SELECT, INSERT, UPDATE, DELETE ON "invitations" TO tajribah_app;
--> statement-breakpoint
ALTER TABLE "invoice_lines" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "invoice_lines" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "invoice_lines"
  USING (tenant_id = current_tenant_id())
  WITH CHECK (tenant_id = current_tenant_id());
GRANT SELECT, INSERT, UPDATE, DELETE ON "invoice_lines" TO tajribah_app;
--> statement-breakpoint
ALTER TABLE "invoice_sequences" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "invoice_sequences" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "invoice_sequences"
  USING (tenant_id = current_tenant_id())
  WITH CHECK (tenant_id = current_tenant_id());
GRANT SELECT, INSERT, UPDATE, DELETE ON "invoice_sequences" TO tajribah_app;
--> statement-breakpoint
ALTER TABLE "invoices" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "invoices" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "invoices"
  USING (tenant_id = current_tenant_id())
  WITH CHECK (tenant_id = current_tenant_id());
GRANT SELECT, INSERT, UPDATE, DELETE ON "invoices" TO tajribah_app;
--> statement-breakpoint
ALTER TABLE "model_files" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "model_files" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "model_files"
  USING (tenant_id = current_tenant_id())
  WITH CHECK (tenant_id = current_tenant_id());
GRANT SELECT, INSERT, UPDATE, DELETE ON "model_files" TO tajribah_app;
--> statement-breakpoint
ALTER TABLE "model_versions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "model_versions" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "model_versions"
  USING (tenant_id = current_tenant_id())
  WITH CHECK (tenant_id = current_tenant_id());
GRANT SELECT, INSERT, UPDATE, DELETE ON "model_versions" TO tajribah_app;
--> statement-breakpoint
ALTER TABLE "models_3d" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "models_3d" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "models_3d"
  USING (tenant_id = current_tenant_id())
  WITH CHECK (tenant_id = current_tenant_id());
GRANT SELECT, INSERT, UPDATE, DELETE ON "models_3d" TO tajribah_app;
--> statement-breakpoint
ALTER TABLE "notifications" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "notifications" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "notifications"
  USING (tenant_id = current_tenant_id())
  WITH CHECK (tenant_id = current_tenant_id());
GRANT SELECT, INSERT, UPDATE, DELETE ON "notifications" TO tajribah_app;
--> statement-breakpoint
ALTER TABLE "payments" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "payments" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "payments"
  USING (tenant_id = current_tenant_id())
  WITH CHECK (tenant_id = current_tenant_id());
GRANT SELECT, INSERT, UPDATE, DELETE ON "payments" TO tajribah_app;
--> statement-breakpoint
ALTER TABLE "product_variants" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "product_variants" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "product_variants"
  USING (tenant_id = current_tenant_id())
  WITH CHECK (tenant_id = current_tenant_id());
GRANT SELECT, INSERT, UPDATE, DELETE ON "product_variants" TO tajribah_app;
--> statement-breakpoint
ALTER TABLE "products" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "products" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "products"
  USING (tenant_id = current_tenant_id())
  WITH CHECK (tenant_id = current_tenant_id());
GRANT SELECT, INSERT, UPDATE, DELETE ON "products" TO tajribah_app;
--> statement-breakpoint
ALTER TABLE "qr_codes" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "qr_codes" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "qr_codes"
  USING (tenant_id = current_tenant_id())
  WITH CHECK (tenant_id = current_tenant_id());
GRANT SELECT, INSERT, UPDATE, DELETE ON "qr_codes" TO tajribah_app;
--> statement-breakpoint
ALTER TABLE "sessions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "sessions" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "sessions"
  USING (tenant_id = current_tenant_id())
  WITH CHECK (tenant_id = current_tenant_id());
GRANT SELECT, INSERT, UPDATE, DELETE ON "sessions" TO tajribah_app;
--> statement-breakpoint
ALTER TABLE "store_connections" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "store_connections" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "store_connections"
  USING (tenant_id = current_tenant_id())
  WITH CHECK (tenant_id = current_tenant_id());
GRANT SELECT, INSERT, UPDATE, DELETE ON "store_connections" TO tajribah_app;
--> statement-breakpoint
ALTER TABLE "subscription_changes" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "subscription_changes" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "subscription_changes"
  USING (tenant_id = current_tenant_id())
  WITH CHECK (tenant_id = current_tenant_id());
GRANT SELECT, INSERT, UPDATE, DELETE ON "subscription_changes" TO tajribah_app;
--> statement-breakpoint
ALTER TABLE "subscriptions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "subscriptions" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "subscriptions"
  USING (tenant_id = current_tenant_id())
  WITH CHECK (tenant_id = current_tenant_id());
GRANT SELECT, INSERT, UPDATE, DELETE ON "subscriptions" TO tajribah_app;
--> statement-breakpoint
ALTER TABLE "sync_job_items" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "sync_job_items" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "sync_job_items"
  USING (tenant_id = current_tenant_id())
  WITH CHECK (tenant_id = current_tenant_id());
GRANT SELECT, INSERT, UPDATE, DELETE ON "sync_job_items" TO tajribah_app;
--> statement-breakpoint
ALTER TABLE "sync_jobs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "sync_jobs" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "sync_jobs"
  USING (tenant_id = current_tenant_id())
  WITH CHECK (tenant_id = current_tenant_id());
GRANT SELECT, INSERT, UPDATE, DELETE ON "sync_jobs" TO tajribah_app;
--> statement-breakpoint
ALTER TABLE "tenant_memberships" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "tenant_memberships" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "tenant_memberships"
  USING (tenant_id = current_tenant_id())
  WITH CHECK (tenant_id = current_tenant_id());
GRANT SELECT, INSERT, UPDATE, DELETE ON "tenant_memberships" TO tajribah_app;
--> statement-breakpoint
ALTER TABLE "tenant_settings" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "tenant_settings" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "tenant_settings"
  USING (tenant_id = current_tenant_id())
  WITH CHECK (tenant_id = current_tenant_id());
GRANT SELECT, INSERT, UPDATE, DELETE ON "tenant_settings" TO tajribah_app;
--> statement-breakpoint
ALTER TABLE "tryon_configs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "tryon_configs" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "tryon_configs"
  USING (tenant_id = current_tenant_id())
  WITH CHECK (tenant_id = current_tenant_id());
GRANT SELECT, INSERT, UPDATE, DELETE ON "tryon_configs" TO tajribah_app;
--> statement-breakpoint
ALTER TABLE "usage_counters" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "usage_counters" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "usage_counters"
  USING (tenant_id = current_tenant_id())
  WITH CHECK (tenant_id = current_tenant_id());
GRANT SELECT, INSERT, UPDATE, DELETE ON "usage_counters" TO tajribah_app;
--> statement-breakpoint
ALTER TABLE "webhook_events" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "webhook_events" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "webhook_events"
  USING (tenant_id = current_tenant_id())
  WITH CHECK (tenant_id = current_tenant_id());
GRANT SELECT, INSERT, UPDATE, DELETE ON "webhook_events" TO tajribah_app;

--> statement-breakpoint

REVOKE ALL ON "plans" FROM tajribah_app;
GRANT SELECT ON "plans" TO tajribah_app;
--> statement-breakpoint
REVOKE ALL ON "plan_limits" FROM tajribah_app;
GRANT SELECT ON "plan_limits" TO tajribah_app;
--> statement-breakpoint
REVOKE ALL ON "plan_features" FROM tajribah_app;
GRANT SELECT ON "plan_features" TO tajribah_app;
--> statement-breakpoint
REVOKE ALL ON "model_registry" FROM tajribah_app;
GRANT SELECT ON "model_registry" TO tajribah_app;

--> statement-breakpoint

GRANT SELECT, INSERT, UPDATE, DELETE ON "feature_flags" TO tajribah_app;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON "jobs" TO tajribah_app;

--> statement-breakpoint

GRANT SELECT, INSERT, UPDATE, DELETE ON "users" TO tajribah_app;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON "tenants" TO tajribah_app;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON "verification_tokens" TO tajribah_app;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON "billing_events" TO tajribah_app;

-- No tenant column (EXEMPT):
--   billing_events
--   model_registry
--   plan_features
--   plan_limits
--   plans
--   refresh_tokens
--   tenants
--   users
--   verification_tokens
--
-- Tenant column, no policy (RLS_EXEMPT):
--   feature_flags
--   jobs

-- ROLLBACK:
-- Executable as written once the leading "-- " is removed; the migration test runs it.
-- Grants are revoked before the roles are dropped: a role that still holds privileges
-- cannot be dropped.
-- DROP POLICY IF EXISTS tenant_isolation ON "ai_job_events";
-- ALTER TABLE "ai_job_events" NO FORCE ROW LEVEL SECURITY;
-- ALTER TABLE "ai_job_events" DISABLE ROW LEVEL SECURITY;
-- DROP POLICY IF EXISTS tenant_isolation ON "ai_jobs";
-- ALTER TABLE "ai_jobs" NO FORCE ROW LEVEL SECURITY;
-- ALTER TABLE "ai_jobs" DISABLE ROW LEVEL SECURITY;
-- DROP POLICY IF EXISTS tenant_isolation ON "analytics_events";
-- ALTER TABLE "analytics_events" NO FORCE ROW LEVEL SECURITY;
-- ALTER TABLE "analytics_events" DISABLE ROW LEVEL SECURITY;
-- DROP POLICY IF EXISTS tenant_isolation ON "api_keys";
-- ALTER TABLE "api_keys" NO FORCE ROW LEVEL SECURITY;
-- ALTER TABLE "api_keys" DISABLE ROW LEVEL SECURITY;
-- DROP POLICY IF EXISTS tenant_isolation ON "ar_configs";
-- ALTER TABLE "ar_configs" NO FORCE ROW LEVEL SECURITY;
-- ALTER TABLE "ar_configs" DISABLE ROW LEVEL SECURITY;
-- DROP POLICY IF EXISTS tenant_isolation ON "audit_logs";
-- ALTER TABLE "audit_logs" NO FORCE ROW LEVEL SECURITY;
-- ALTER TABLE "audit_logs" DISABLE ROW LEVEL SECURITY;
-- DROP POLICY IF EXISTS tenant_isolation ON "categories";
-- ALTER TABLE "categories" NO FORCE ROW LEVEL SECURITY;
-- ALTER TABLE "categories" DISABLE ROW LEVEL SECURITY;
-- DROP POLICY IF EXISTS tenant_isolation ON "conversion_daily";
-- ALTER TABLE "conversion_daily" NO FORCE ROW LEVEL SECURITY;
-- ALTER TABLE "conversion_daily" DISABLE ROW LEVEL SECURITY;
-- DROP POLICY IF EXISTS tenant_isolation ON "credit_ledger";
-- ALTER TABLE "credit_ledger" NO FORCE ROW LEVEL SECURITY;
-- ALTER TABLE "credit_ledger" DISABLE ROW LEVEL SECURITY;
-- DROP POLICY IF EXISTS tenant_isolation ON "daily_product_stats";
-- ALTER TABLE "daily_product_stats" NO FORCE ROW LEVEL SECURITY;
-- ALTER TABLE "daily_product_stats" DISABLE ROW LEVEL SECURITY;
-- DROP POLICY IF EXISTS tenant_isolation ON "daily_tenant_stats";
-- ALTER TABLE "daily_tenant_stats" NO FORCE ROW LEVEL SECURITY;
-- ALTER TABLE "daily_tenant_stats" DISABLE ROW LEVEL SECURITY;
-- DROP POLICY IF EXISTS tenant_isolation ON "data_requests";
-- ALTER TABLE "data_requests" NO FORCE ROW LEVEL SECURITY;
-- ALTER TABLE "data_requests" DISABLE ROW LEVEL SECURITY;
-- DROP POLICY IF EXISTS tenant_isolation ON "device_breakdown_daily";
-- ALTER TABLE "device_breakdown_daily" NO FORCE ROW LEVEL SECURITY;
-- ALTER TABLE "device_breakdown_daily" DISABLE ROW LEVEL SECURITY;
-- DROP POLICY IF EXISTS tenant_isolation ON "field_mappings";
-- ALTER TABLE "field_mappings" NO FORCE ROW LEVEL SECURITY;
-- ALTER TABLE "field_mappings" DISABLE ROW LEVEL SECURITY;
-- DROP POLICY IF EXISTS tenant_isolation ON "generation_inputs";
-- ALTER TABLE "generation_inputs" NO FORCE ROW LEVEL SECURITY;
-- ALTER TABLE "generation_inputs" DISABLE ROW LEVEL SECURITY;
-- DROP POLICY IF EXISTS tenant_isolation ON "hosted_pages";
-- ALTER TABLE "hosted_pages" NO FORCE ROW LEVEL SECURITY;
-- ALTER TABLE "hosted_pages" DISABLE ROW LEVEL SECURITY;
-- DROP POLICY IF EXISTS tenant_isolation ON "invitations";
-- ALTER TABLE "invitations" NO FORCE ROW LEVEL SECURITY;
-- ALTER TABLE "invitations" DISABLE ROW LEVEL SECURITY;
-- DROP POLICY IF EXISTS tenant_isolation ON "invoice_lines";
-- ALTER TABLE "invoice_lines" NO FORCE ROW LEVEL SECURITY;
-- ALTER TABLE "invoice_lines" DISABLE ROW LEVEL SECURITY;
-- DROP POLICY IF EXISTS tenant_isolation ON "invoice_sequences";
-- ALTER TABLE "invoice_sequences" NO FORCE ROW LEVEL SECURITY;
-- ALTER TABLE "invoice_sequences" DISABLE ROW LEVEL SECURITY;
-- DROP POLICY IF EXISTS tenant_isolation ON "invoices";
-- ALTER TABLE "invoices" NO FORCE ROW LEVEL SECURITY;
-- ALTER TABLE "invoices" DISABLE ROW LEVEL SECURITY;
-- DROP POLICY IF EXISTS tenant_isolation ON "model_files";
-- ALTER TABLE "model_files" NO FORCE ROW LEVEL SECURITY;
-- ALTER TABLE "model_files" DISABLE ROW LEVEL SECURITY;
-- DROP POLICY IF EXISTS tenant_isolation ON "model_versions";
-- ALTER TABLE "model_versions" NO FORCE ROW LEVEL SECURITY;
-- ALTER TABLE "model_versions" DISABLE ROW LEVEL SECURITY;
-- DROP POLICY IF EXISTS tenant_isolation ON "models_3d";
-- ALTER TABLE "models_3d" NO FORCE ROW LEVEL SECURITY;
-- ALTER TABLE "models_3d" DISABLE ROW LEVEL SECURITY;
-- DROP POLICY IF EXISTS tenant_isolation ON "notifications";
-- ALTER TABLE "notifications" NO FORCE ROW LEVEL SECURITY;
-- ALTER TABLE "notifications" DISABLE ROW LEVEL SECURITY;
-- DROP POLICY IF EXISTS tenant_isolation ON "payments";
-- ALTER TABLE "payments" NO FORCE ROW LEVEL SECURITY;
-- ALTER TABLE "payments" DISABLE ROW LEVEL SECURITY;
-- DROP POLICY IF EXISTS tenant_isolation ON "product_variants";
-- ALTER TABLE "product_variants" NO FORCE ROW LEVEL SECURITY;
-- ALTER TABLE "product_variants" DISABLE ROW LEVEL SECURITY;
-- DROP POLICY IF EXISTS tenant_isolation ON "products";
-- ALTER TABLE "products" NO FORCE ROW LEVEL SECURITY;
-- ALTER TABLE "products" DISABLE ROW LEVEL SECURITY;
-- DROP POLICY IF EXISTS tenant_isolation ON "qr_codes";
-- ALTER TABLE "qr_codes" NO FORCE ROW LEVEL SECURITY;
-- ALTER TABLE "qr_codes" DISABLE ROW LEVEL SECURITY;
-- DROP POLICY IF EXISTS tenant_isolation ON "sessions";
-- ALTER TABLE "sessions" NO FORCE ROW LEVEL SECURITY;
-- ALTER TABLE "sessions" DISABLE ROW LEVEL SECURITY;
-- DROP POLICY IF EXISTS tenant_isolation ON "store_connections";
-- ALTER TABLE "store_connections" NO FORCE ROW LEVEL SECURITY;
-- ALTER TABLE "store_connections" DISABLE ROW LEVEL SECURITY;
-- DROP POLICY IF EXISTS tenant_isolation ON "subscription_changes";
-- ALTER TABLE "subscription_changes" NO FORCE ROW LEVEL SECURITY;
-- ALTER TABLE "subscription_changes" DISABLE ROW LEVEL SECURITY;
-- DROP POLICY IF EXISTS tenant_isolation ON "subscriptions";
-- ALTER TABLE "subscriptions" NO FORCE ROW LEVEL SECURITY;
-- ALTER TABLE "subscriptions" DISABLE ROW LEVEL SECURITY;
-- DROP POLICY IF EXISTS tenant_isolation ON "sync_job_items";
-- ALTER TABLE "sync_job_items" NO FORCE ROW LEVEL SECURITY;
-- ALTER TABLE "sync_job_items" DISABLE ROW LEVEL SECURITY;
-- DROP POLICY IF EXISTS tenant_isolation ON "sync_jobs";
-- ALTER TABLE "sync_jobs" NO FORCE ROW LEVEL SECURITY;
-- ALTER TABLE "sync_jobs" DISABLE ROW LEVEL SECURITY;
-- DROP POLICY IF EXISTS tenant_isolation ON "tenant_memberships";
-- ALTER TABLE "tenant_memberships" NO FORCE ROW LEVEL SECURITY;
-- ALTER TABLE "tenant_memberships" DISABLE ROW LEVEL SECURITY;
-- DROP POLICY IF EXISTS tenant_isolation ON "tenant_settings";
-- ALTER TABLE "tenant_settings" NO FORCE ROW LEVEL SECURITY;
-- ALTER TABLE "tenant_settings" DISABLE ROW LEVEL SECURITY;
-- DROP POLICY IF EXISTS tenant_isolation ON "tryon_configs";
-- ALTER TABLE "tryon_configs" NO FORCE ROW LEVEL SECURITY;
-- ALTER TABLE "tryon_configs" DISABLE ROW LEVEL SECURITY;
-- DROP POLICY IF EXISTS tenant_isolation ON "usage_counters";
-- ALTER TABLE "usage_counters" NO FORCE ROW LEVEL SECURITY;
-- ALTER TABLE "usage_counters" DISABLE ROW LEVEL SECURITY;
-- DROP POLICY IF EXISTS tenant_isolation ON "webhook_events";
-- ALTER TABLE "webhook_events" NO FORCE ROW LEVEL SECURITY;
-- ALTER TABLE "webhook_events" DISABLE ROW LEVEL SECURITY;
-- REVOKE ALL ON ALL TABLES IN SCHEMA public FROM tajribah_app, tajribah_admin;
-- REVOKE ALL ON SCHEMA public FROM tajribah_app, tajribah_admin;
-- DROP FUNCTION IF EXISTS current_tenant_id();
-- DROP ROLE IF EXISTS tajribah_admin;
-- DROP ROLE IF EXISTS tajribah_app;
