-- P2.12: coupons. `coupons` is a platform catalogue (like `plans`): the app role may only read
-- it; the admin console writes it. `coupon_redemptions` is tenant data under the usual policy,
-- one per store per coupon (the unique index), so a code cannot be used twice by one store.
-- Their RLS lines are generated into this file by scripts/gen-rls.mjs (below, between markers):
-- 0001 ran before these tables existed.
CREATE TYPE "public"."coupon_kind" AS ENUM('percent', 'fixed', 'free_months');
--> statement-breakpoint
CREATE TABLE "coupons" (
	"id" uuid PRIMARY KEY NOT NULL,
	"code" text NOT NULL,
	"kind" "coupon_kind" NOT NULL,
	"percent_off" integer,
	"amount_off_minor" integer,
	"free_months" integer,
	"applies_to" jsonb,
	"max_redemptions" integer,
	"valid_from" timestamp with time zone,
	"valid_until" timestamp with time zone,
	"active" boolean DEFAULT true NOT NULL,
	"note" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX "coupons_code_unq" ON "coupons" USING btree ("code");
--> statement-breakpoint
CREATE TABLE "coupon_redemptions" (
	"id" uuid PRIMARY KEY NOT NULL,
	"tenant_id" uuid NOT NULL,
	"coupon_id" uuid NOT NULL,
	"subscription_id" uuid,
	"invoice_id" uuid,
	"discount_minor" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "coupon_redemptions" ADD CONSTRAINT "coupon_redemptions_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "coupon_redemptions" ADD CONSTRAINT "coupon_redemptions_coupon_id_coupons_id_fk" FOREIGN KEY ("coupon_id") REFERENCES "public"."coupons"("id") ON DELETE restrict ON UPDATE no action;
--> statement-breakpoint
CREATE UNIQUE INDEX "coupon_redemptions_once_unq" ON "coupon_redemptions" USING btree ("coupon_id", "tenant_id");
--> statement-breakpoint
CREATE INDEX "coupon_redemptions_tenant_idx" ON "coupon_redemptions" USING btree ("tenant_id");

--> statement-breakpoint
-- rls:begin — GENERATED by scripts/gen-rls.mjs from db/schema; do not hand-edit
--> statement-breakpoint
ALTER TABLE "coupon_redemptions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "coupon_redemptions" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "coupon_redemptions"
  USING (tenant_id = current_tenant_id())
  WITH CHECK (tenant_id = current_tenant_id());
GRANT SELECT, INSERT, UPDATE, DELETE ON "coupon_redemptions" TO tajribah_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON "coupon_redemptions" TO tajribah_admin;
--> statement-breakpoint
REVOKE ALL ON "coupons" FROM tajribah_app;
GRANT SELECT ON "coupons" TO tajribah_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON "coupons" TO tajribah_admin;
-- rls:end

-- ROLLBACK:
-- DROP TABLE IF EXISTS "coupon_redemptions";
-- DROP TABLE IF EXISTS "coupons";
-- DROP TYPE IF EXISTS "coupon_kind";
