-- A1: what Tajribah staff did in the admin console. Platform-wide (an action may concern no
-- store at all, like a coupon or a plan), so it cannot live in audit_logs, whose tenant_id is
-- required. Admin role only: the application role gets no grant at all, so a merchant request
-- can neither read nor write it (the generated block below says so). `store_id` names the store
-- an action concerned, when it concerned one — deliberately not `tenant_id`: this is not tenant
-- data and must not get a tenant policy.
CREATE TABLE "staff_audit" (
	"id" uuid PRIMARY KEY NOT NULL,
	"staff_user_id" uuid NOT NULL,
	"action" text NOT NULL,
	"target_type" text NOT NULL,
	"target_id" text,
	"store_id" uuid,
	"reason" text,
	"detail" jsonb,
	"request_id" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "staff_audit" ADD CONSTRAINT "staff_audit_staff_user_id_users_id_fk" FOREIGN KEY ("staff_user_id") REFERENCES "public"."users"("id") ON DELETE restrict ON UPDATE no action;
--> statement-breakpoint
CREATE INDEX "staff_audit_time_idx" ON "staff_audit" USING btree ("created_at");
--> statement-breakpoint
CREATE INDEX "staff_audit_store_idx" ON "staff_audit" USING btree ("store_id", "created_at");

--> statement-breakpoint
-- rls:begin — GENERATED by scripts/gen-rls.mjs from db/schema; do not hand-edit
--> statement-breakpoint
-- "staff_audit": no tenant column and no app grant — admin role only (EXEMPT).
GRANT SELECT, INSERT, UPDATE, DELETE ON "staff_audit" TO tajribah_admin;
-- rls:end

-- ROLLBACK:
-- DROP TABLE IF EXISTS "staff_audit";
