-- A13 (T23): announcements — the platform copy staff change without a deploy: a bilingual notice
-- shown on every store's dashboard between two times (maintenance, a new feature, holiday
-- support hours). A platform catalogue like `coupons`: the app role may only read it; the
-- admin console writes it. Its RLS lines are generated below by scripts/gen-rls.mjs.
CREATE TYPE "public"."announcement_level" AS ENUM('info', 'warning');
--> statement-breakpoint
CREATE TABLE "announcements" (
	"id" uuid PRIMARY KEY NOT NULL,
	"title_ar" text NOT NULL,
	"title_en" text NOT NULL,
	"body_ar" text,
	"body_en" text,
	"level" "announcement_level" DEFAULT 'info' NOT NULL,
	"link" text,
	"starts_at" timestamp with time zone NOT NULL,
	"ends_at" timestamp with time zone NOT NULL,
	"active" boolean DEFAULT true NOT NULL,
	"created_by" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE INDEX "announcements_window_idx" ON "announcements" USING btree ("active", "starts_at", "ends_at");

--> statement-breakpoint
-- rls:begin — GENERATED by scripts/gen-rls.mjs from db/schema; do not hand-edit
--> statement-breakpoint
REVOKE ALL ON "announcements" FROM tajribah_app;
GRANT SELECT ON "announcements" TO tajribah_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON "announcements" TO tajribah_admin;
-- rls:end

-- ROLLBACK:
-- DROP TABLE IF EXISTS "announcements";
-- DROP TYPE IF EXISTS "announcement_level";
