-- P3.3: product photos for 3D generation, uploaded and checked before any credits are spent.
-- They exist before the generation job does, so they cannot live in `generation_inputs` (whose
-- job_id is required); a starting generation copies its accepted photos there. Tenant data under
-- the usual policy; its RLS lines are generated into this file by scripts/gen-rls.mjs (below).
CREATE TYPE "public"."generation_photo_status" AS ENUM('uploading', 'accepted', 'rejected');
--> statement-breakpoint
CREATE TABLE "generation_photos" (
	"id" uuid PRIMARY KEY NOT NULL,
	"tenant_id" uuid NOT NULL,
	"product_id" uuid NOT NULL,
	"angle" "generation_angle" NOT NULL,
	"status" "generation_photo_status" DEFAULT 'uploading' NOT NULL,
	"storage_key" text NOT NULL,
	"original_filename" text,
	"format" text,
	"size_bytes" integer,
	"width" integer,
	"height" integer,
	"sha256" text,
	"quality_score" integer,
	"issues" jsonb,
	"bytes_deleted_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "generation_photos" ADD CONSTRAINT "generation_photos_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "generation_photos" ADD CONSTRAINT "generation_photos_product_id_products_id_fk" FOREIGN KEY ("product_id") REFERENCES "public"."products"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
CREATE INDEX "generation_photos_product_idx" ON "generation_photos" USING btree ("tenant_id", "product_id", "status");

--> statement-breakpoint
-- rls:begin — GENERATED by scripts/gen-rls.mjs from db/schema; do not hand-edit
--> statement-breakpoint
ALTER TABLE "generation_photos" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "generation_photos" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "generation_photos"
  USING (tenant_id = current_tenant_id())
  WITH CHECK (tenant_id = current_tenant_id());
GRANT SELECT, INSERT, UPDATE, DELETE ON "generation_photos" TO tajribah_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON "generation_photos" TO tajribah_admin;
-- rls:end

-- ROLLBACK:
-- DROP TABLE IF EXISTS "generation_photos";
-- DROP TYPE IF EXISTS "generation_photo_status";
