-- P1.15: what each product has live at the edge (the config the shop's widget and the try-on page
-- read). One row per product: the key written, a version bumped on every write, the fingerprint of
-- what was written, and when it was published or withdrawn. Tenant data under the usual policy;
-- its RLS lines are generated into this file by scripts/gen-rls.mjs (below).
CREATE TABLE "edge_configs" (
	"id" uuid PRIMARY KEY NOT NULL,
	"tenant_id" uuid NOT NULL,
	"product_id" uuid NOT NULL,
	"key" text,
	"version" integer DEFAULT 0 NOT NULL,
	"fingerprint" text,
	"published_at" timestamp with time zone,
	"withdrawn_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "edge_configs" ADD CONSTRAINT "edge_configs_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "edge_configs" ADD CONSTRAINT "edge_configs_product_id_products_id_fk" FOREIGN KEY ("product_id") REFERENCES "public"."products"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
CREATE UNIQUE INDEX "edge_configs_product_unq" ON "edge_configs" USING btree ("product_id");

--> statement-breakpoint
-- rls:begin — GENERATED by scripts/gen-rls.mjs from db/schema; do not hand-edit
--> statement-breakpoint
ALTER TABLE "edge_configs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "edge_configs" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "edge_configs"
  USING (tenant_id = current_tenant_id())
  WITH CHECK (tenant_id = current_tenant_id());
GRANT SELECT, INSERT, UPDATE, DELETE ON "edge_configs" TO tajribah_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON "edge_configs" TO tajribah_admin;
-- rls:end

-- ROLLBACK:
-- DROP TABLE IF EXISTS "edge_configs";
