-- P6.7: the brakes staff can pull on AI spend. One row (id 'platform', enforced below): the kinds of
-- work paused, a platform daily spend cap in US cents and a per-store daily job cap. No row, or a
-- null, means no limit — no number is chosen here; staff set them in the admin console. Platform
-- data, admin role only (EXEMPT); its grant line is generated into this file by scripts/gen-rls.mjs.
CREATE TABLE "ai_guardrails" (
	"id" text PRIMARY KEY NOT NULL CHECK ("id" = 'platform'),
	"paused_types" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"daily_spend_cap_cents" integer CHECK ("daily_spend_cap_cents" >= 0),
	"store_daily_jobs_cap" integer CHECK ("store_daily_jobs_cap" >= 0),
	"updated_by" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
-- Today's spend across every store is summed before each new job is charged: by creation time.
-- CONCURRENTLY: ai_jobs is written by the running version (outside a transaction, P7's runner).
CREATE INDEX CONCURRENTLY IF NOT EXISTS "ai_jobs_created_idx" ON "ai_jobs" USING btree ("created_at");

--> statement-breakpoint
-- rls:begin — GENERATED by scripts/gen-rls.mjs from db/schema; do not hand-edit
--> statement-breakpoint
-- "ai_guardrails": no tenant column and no app grant — admin role only (EXEMPT).
GRANT SELECT, INSERT, UPDATE, DELETE ON "ai_guardrails" TO tajribah_admin;
-- rls:end

-- ROLLBACK:
-- DROP INDEX IF EXISTS "ai_jobs_created_idx";
-- DROP TABLE IF EXISTS "ai_guardrails";
