-- P8: custom roles (Enterprise) — a store's own named sets of permissions, and the member who holds
-- one. Expand-only: a new table, and a nullable column on tenant_memberships whose foreign key is
-- added NOT VALID (no write lock while it is checked) and validated in its own statement (every
-- existing row is null, so the check is instant and blocks no writes).
CREATE TABLE "custom_roles" (
	"id" uuid PRIMARY KEY NOT NULL,
	"tenant_id" uuid NOT NULL REFERENCES "public"."tenants"("id") ON DELETE cascade,
	"name" text NOT NULL,
	"permissions" jsonb NOT NULL,
	"created_by" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE INDEX "custom_roles_tenant_idx" ON "custom_roles" USING btree ("tenant_id");
--> statement-breakpoint
ALTER TABLE "tenant_memberships" ADD COLUMN "custom_role_id" uuid;
--> statement-breakpoint
ALTER TABLE "tenant_memberships" ADD CONSTRAINT "tenant_memberships_custom_role_id_custom_roles_id_fk" FOREIGN KEY ("custom_role_id") REFERENCES "public"."custom_roles"("id") NOT VALID;
--> statement-breakpoint
ALTER TABLE "tenant_memberships" VALIDATE CONSTRAINT "tenant_memberships_custom_role_id_custom_roles_id_fk";

--> statement-breakpoint
-- rls:begin — GENERATED by scripts/gen-rls.mjs from db/schema; do not hand-edit
--> statement-breakpoint
ALTER TABLE "custom_roles" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "custom_roles" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "custom_roles"
  USING (tenant_id = current_tenant_id())
  WITH CHECK (tenant_id = current_tenant_id());
GRANT SELECT, INSERT, UPDATE, DELETE ON "custom_roles" TO tajribah_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON "custom_roles" TO tajribah_admin;
-- rls:end

-- ROLLBACK:
-- ALTER TABLE "tenant_memberships" DROP CONSTRAINT IF EXISTS "tenant_memberships_custom_role_id_custom_roles_id_fk";
-- ALTER TABLE "tenant_memberships" DROP COLUMN IF EXISTS "custom_role_id";
-- DROP TABLE IF EXISTS "custom_roles";
