-- P8: single sign-on (Enterprise) — one OpenID Connect provider per store, the members' identities
-- at it, and the store an SSO session is locked to. Expand-only: two new tables and a nullable column.
CREATE TABLE "sso_connections" (
	"id" uuid PRIMARY KEY NOT NULL,
	"tenant_id" uuid NOT NULL REFERENCES "public"."tenants"("id") ON DELETE cascade,
	"issuer" text NOT NULL,
	"client_id" text NOT NULL,
	"client_secret_encrypted" text NOT NULL,
	"email_domains" jsonb NOT NULL,
	"enabled" boolean DEFAULT false NOT NULL,
	"created_by" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX "sso_connections_tenant_unq" ON "sso_connections" USING btree ("tenant_id");
--> statement-breakpoint
CREATE TABLE "sso_identities" (
	"id" uuid PRIMARY KEY NOT NULL,
	"tenant_id" uuid NOT NULL REFERENCES "public"."tenants"("id") ON DELETE cascade,
	"user_id" uuid NOT NULL REFERENCES "public"."users"("id") ON DELETE cascade,
	"issuer" text NOT NULL,
	"subject" text NOT NULL,
	"last_login_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX "sso_identities_subject_unq" ON "sso_identities" USING btree ("tenant_id","issuer","subject");
--> statement-breakpoint
ALTER TABLE "sessions" ADD COLUMN "sso_tenant_id" uuid;

--> statement-breakpoint
-- rls:begin — GENERATED by scripts/gen-rls.mjs from db/schema; do not hand-edit
--> statement-breakpoint
ALTER TABLE "sso_connections" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "sso_connections" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "sso_connections"
  USING (tenant_id = current_tenant_id())
  WITH CHECK (tenant_id = current_tenant_id());
GRANT SELECT, INSERT, UPDATE, DELETE ON "sso_connections" TO tajribah_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON "sso_connections" TO tajribah_admin;
--> statement-breakpoint
ALTER TABLE "sso_identities" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "sso_identities" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "sso_identities"
  USING (tenant_id = current_tenant_id())
  WITH CHECK (tenant_id = current_tenant_id());
GRANT SELECT, INSERT, UPDATE, DELETE ON "sso_identities" TO tajribah_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON "sso_identities" TO tajribah_admin;
-- rls:end

-- ROLLBACK:
-- ALTER TABLE "sessions" DROP COLUMN IF EXISTS "sso_tenant_id";
-- DROP TABLE IF EXISTS "sso_identities";
-- DROP TABLE IF EXISTS "sso_connections";
