-- T61: a store platform's access for a store no Tajribah account has linked yet. Salla hands a
-- store's tokens over by webhook when the merchant installs the app; they wait here, sealed, until the
-- merchant links the store from inside Salla. Expand-only: one new table. Platform data, admin role
-- only (EXEMPT); its grant line is generated into this file by scripts/gen-rls.mjs.
CREATE TABLE "store_grants" (
	"id" uuid PRIMARY KEY NOT NULL,
	"provider" "provider" NOT NULL,
	"external_store_id" text NOT NULL,
	"access_token_encrypted" text,
	"refresh_token_encrypted" text,
	"token_expires_at" timestamp with time zone,
	"scopes" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX "store_grants_provider_store_unq" ON "store_grants" USING btree ("provider","external_store_id");

--> statement-breakpoint
-- rls:begin — GENERATED by scripts/gen-rls.mjs from db/schema; do not hand-edit
--> statement-breakpoint
-- "store_grants": no tenant column and no app grant — admin role only (EXEMPT).
GRANT SELECT, INSERT, UPDATE, DELETE ON "store_grants" TO tajribah_admin;
-- rls:end

-- ROLLBACK:
-- DROP TABLE IF EXISTS "store_grants";
