-- T62: an Enterprise store's own address for its AR and try-on pages. One per store; a hostname
-- belongs to one store at most. Expand-only: a new type and a new table.
CREATE TYPE "public"."custom_domain_status" AS ENUM('pending', 'verified', 'ready', 'active');
--> statement-breakpoint
CREATE TABLE "custom_domains" (
	"id" uuid PRIMARY KEY NOT NULL,
	"tenant_id" uuid NOT NULL REFERENCES "public"."tenants"("id") ON DELETE cascade,
	"hostname" text NOT NULL,
	"token" text NOT NULL,
	"status" "custom_domain_status" DEFAULT 'pending' NOT NULL,
	"verified_at" timestamp with time zone,
	"checked_at" timestamp with time zone,
	"last_problem" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX "custom_domains_hostname_unq" ON "custom_domains" USING btree ("hostname");
--> statement-breakpoint
CREATE UNIQUE INDEX "custom_domains_tenant_unq" ON "custom_domains" USING btree ("tenant_id");

--> statement-breakpoint
-- rls:begin — GENERATED by scripts/gen-rls.mjs from db/schema; do not hand-edit
--> statement-breakpoint
ALTER TABLE "custom_domains" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "custom_domains" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "custom_domains"
  USING (tenant_id = current_tenant_id())
  WITH CHECK (tenant_id = current_tenant_id());
GRANT SELECT, INSERT, UPDATE, DELETE ON "custom_domains" TO tajribah_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON "custom_domains" TO tajribah_admin;
-- rls:end

-- ROLLBACK:
-- DROP TABLE IF EXISTS "custom_domains";
-- DROP TYPE IF EXISTS "public"."custom_domain_status";
