-- P4.8: a member's choice to get the store's weekly analytics summary by email. One row per member
-- per store. Expand-only: a new table.
CREATE TABLE "report_subscriptions" (
	"id" uuid PRIMARY KEY NOT NULL,
	"tenant_id" uuid NOT NULL REFERENCES "public"."tenants"("id") ON DELETE cascade,
	"user_id" uuid NOT NULL REFERENCES "public"."users"("id") ON DELETE cascade,
	"last_sent_for" date,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX "report_subscriptions_member_unq" ON "report_subscriptions" USING btree ("tenant_id","user_id");
--> statement-breakpoint
CREATE INDEX "report_subscriptions_due_idx" ON "report_subscriptions" USING btree ("last_sent_for");

--> statement-breakpoint
-- rls:begin — GENERATED by scripts/gen-rls.mjs from db/schema; do not hand-edit
--> statement-breakpoint
ALTER TABLE "report_subscriptions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "report_subscriptions" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "report_subscriptions"
  USING (tenant_id = current_tenant_id())
  WITH CHECK (tenant_id = current_tenant_id());
GRANT SELECT, INSERT, UPDATE, DELETE ON "report_subscriptions" TO tajribah_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON "report_subscriptions" TO tajribah_admin;
-- rls:end

-- ROLLBACK:
-- DROP TABLE IF EXISTS "report_subscriptions";
