-- P3.10: a professional 3D model, made by Tajribah's team for one product ("Professional 3D modelling,
-- priced per product" on the website). The merchant asks; staff quote a price; paying opens with the
-- payment gateway (P2.3). One open order per product. Expand-only: a new type and a new table.
CREATE TYPE "public"."professional_order_status" AS ENUM('requested', 'quoted', 'accepted', 'delivered', 'cancelled');
--> statement-breakpoint
CREATE TABLE "professional_orders" (
	"id" uuid PRIMARY KEY NOT NULL,
	"tenant_id" uuid NOT NULL REFERENCES "public"."tenants"("id") ON DELETE cascade,
	"product_id" uuid NOT NULL REFERENCES "public"."products"("id") ON DELETE cascade,
	"status" "professional_order_status" DEFAULT 'requested' NOT NULL,
	"note" text,
	"requested_by" uuid,
	"price_minor" integer,
	"currency" text DEFAULT 'SAR' NOT NULL,
	"quote_note" text,
	"quoted_at" timestamp with time zone,
	"quoted_by" uuid,
	"cancelled_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX "professional_orders_open_unq" ON "professional_orders" USING btree ("product_id") WHERE "status" IN ('requested', 'quoted', 'accepted');
--> statement-breakpoint
CREATE INDEX "professional_orders_tenant_idx" ON "professional_orders" USING btree ("tenant_id", "created_at");
--> statement-breakpoint
CREATE INDEX "professional_orders_status_idx" ON "professional_orders" USING btree ("status", "created_at");

--> statement-breakpoint
-- rls:begin — GENERATED by scripts/gen-rls.mjs from db/schema; do not hand-edit
--> statement-breakpoint
ALTER TABLE "professional_orders" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "professional_orders" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "professional_orders"
  USING (tenant_id = current_tenant_id())
  WITH CHECK (tenant_id = current_tenant_id());
GRANT SELECT, INSERT, UPDATE, DELETE ON "professional_orders" TO tajribah_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON "professional_orders" TO tajribah_admin;
-- rls:end

-- ROLLBACK:
-- DROP TABLE IF EXISTS "professional_orders";
-- DROP TYPE IF EXISTS "public"."professional_order_status";
