-- Recommendations, first version (your choice, 2026-10-03: no AI): products often viewed together —
-- each product's top four by visits that looked at both in the last 30 days, recomputed nightly from the
-- analytics events; and when each store was last computed. Expand-only: two new tables.
CREATE TABLE "product_relations" (
	"id" uuid PRIMARY KEY NOT NULL,
	"tenant_id" uuid NOT NULL REFERENCES "public"."tenants"("id") ON DELETE cascade,
	"product_id" uuid NOT NULL REFERENCES "public"."products"("id") ON DELETE cascade,
	"related_product_id" uuid NOT NULL REFERENCES "public"."products"("id") ON DELETE cascade,
	"sessions" integer NOT NULL,
	"rank" integer NOT NULL,
	"computed_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX "product_relations_pair_unq" ON "product_relations" USING btree ("product_id", "related_product_id");
--> statement-breakpoint
CREATE INDEX "product_relations_tenant_idx" ON "product_relations" USING btree ("tenant_id", "product_id", "rank");
--> statement-breakpoint
CREATE TABLE "relation_runs" (
	"tenant_id" uuid PRIMARY KEY NOT NULL REFERENCES "public"."tenants"("id") ON DELETE cascade,
	"day" date NOT NULL,
	"pairs" integer DEFAULT 0 NOT NULL,
	"computed_at" timestamp with time zone DEFAULT now() NOT NULL
);

--> statement-breakpoint
-- rls:begin — GENERATED by scripts/gen-rls.mjs from db/schema; do not hand-edit
--> statement-breakpoint
ALTER TABLE "product_relations" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "product_relations" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "product_relations"
  USING (tenant_id = current_tenant_id())
  WITH CHECK (tenant_id = current_tenant_id());
GRANT SELECT, INSERT, UPDATE, DELETE ON "product_relations" TO tajribah_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON "product_relations" TO tajribah_admin;
--> statement-breakpoint
ALTER TABLE "relation_runs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "relation_runs" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "relation_runs"
  USING (tenant_id = current_tenant_id())
  WITH CHECK (tenant_id = current_tenant_id());
GRANT SELECT, INSERT, UPDATE, DELETE ON "relation_runs" TO tajribah_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON "relation_runs" TO tajribah_admin;
-- rls:end

-- ROLLBACK:
-- DROP TABLE IF EXISTS "relation_runs";
-- DROP TABLE IF EXISTS "product_relations";
