-- T69: GA4 measurement ids set from the dashboard instead of a build variable.
--  - site_settings: the website's own settings (its GA4 id), written by the admin console and
--    published to the config store. Admin role only — no store reads it.
--  - tenant_settings.ga4_measurement_id: a store's own GA4 id, for its products' own pages.
-- Expand-only: a new table and a nullable column.
CREATE TABLE "site_settings" (
	"key" text PRIMARY KEY NOT NULL,
	"value" jsonb NOT NULL,
	"updated_by" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "tenant_settings" ADD COLUMN "ga4_measurement_id" text;

--> statement-breakpoint
-- rls:begin — GENERATED by scripts/gen-rls.mjs from db/schema; do not hand-edit
--> statement-breakpoint
-- "site_settings": no tenant column and no app grant — admin role only (EXEMPT).
GRANT SELECT, INSERT, UPDATE, DELETE ON "site_settings" TO tajribah_admin;
-- rls:end

-- ROLLBACK:
-- ALTER TABLE "tenant_settings" DROP COLUMN IF EXISTS "ga4_measurement_id";
-- DROP TABLE IF EXISTS "site_settings";
