-- Uploads started and never confirmed: try-on pictures and model pictures have no row of their own
-- until they are attached, so bytes sent without a confirm (a tab closed mid-upload) were never
-- deleted. Start records the key here, confirm removes it, and a sweep deletes what is left after a
-- day. Expand-only: a new table.
CREATE TABLE "pending_uploads" (
	"id" uuid PRIMARY KEY NOT NULL,
	"tenant_id" uuid NOT NULL,
	"storage_key" text NOT NULL,
	"purpose" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "pending_uploads" ADD CONSTRAINT "pending_uploads_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
CREATE UNIQUE INDEX "pending_uploads_key_idx" ON "pending_uploads" USING btree ("tenant_id","storage_key");
--> statement-breakpoint
CREATE INDEX "pending_uploads_created_idx" ON "pending_uploads" USING btree ("created_at");

--> statement-breakpoint
-- rls:begin — GENERATED by scripts/gen-rls.mjs from db/schema; do not hand-edit
--> statement-breakpoint
ALTER TABLE "pending_uploads" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "pending_uploads" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "pending_uploads"
  USING (tenant_id = current_tenant_id())
  WITH CHECK (tenant_id = current_tenant_id());
GRANT SELECT, INSERT, UPDATE, DELETE ON "pending_uploads" TO tajribah_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON "pending_uploads" TO tajribah_admin;
-- rls:end

-- ROLLBACK:
-- DROP TABLE IF EXISTS "pending_uploads";
