-- T115: the website's contact form stores its messages here instead of opening the visitor's mail app
-- (Nader, 2026-10-08); staff read them in the admin console («رسائل التواصل»).
--  - contact_status: new → read → archived (staff move them; a message can go back to new).
--  - contact_messages: one row per message. Admin role only — the public form writes through the admin role
--    after Turnstile, a rate limit and a trap field; no store ever reads it.
-- Expand-only: a new enum and a new table, unread by the running version.
CREATE TYPE "public"."contact_status" AS ENUM('new', 'read', 'archived');
--> statement-breakpoint
CREATE TABLE "contact_messages" (
	"id" uuid PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"email" text NOT NULL,
	"phone" text,
	"store_url" text,
	"platform" text,
	"message" text NOT NULL,
	"lang" text NOT NULL,
	"status" "contact_status" DEFAULT 'new' NOT NULL,
	"ip_hash" text,
	"user_agent" text,
	"handled_by" uuid,
	"handled_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE INDEX "contact_messages_status_idx" ON "contact_messages" USING btree ("status","created_at");

--> statement-breakpoint
-- rls:begin — GENERATED by scripts/gen-rls.mjs from db/schema; do not hand-edit
--> statement-breakpoint
-- "contact_messages": no tenant column and no app grant — admin role only (EXEMPT).
GRANT SELECT, INSERT, UPDATE, DELETE ON "contact_messages" TO tajribah_admin;
-- rls:end

-- ROLLBACK:
-- DROP TABLE IF EXISTS "contact_messages";
-- DROP TYPE IF EXISTS "public"."contact_status";
