/**
 * Which paths are the website's (app/(site), moved here from tajribah-try-on) rather than the
 * dashboard's. The proxy gives the website its own page policy (GA, the try-on's camera and wasm,
 * framing for /embed) and the dashboard its stricter one. Generated by hand from the folders under
 * app/(site); `lib/__tests__/site-paths.test.ts` fails when a page is added there and not here.
 */
export const SITE_PAGES = [
  '/', '/about', '/blog', '/blog/[slug]', '/capture/[token]', '/careers', '/contact', '/cookies', '/customers',
  '/demo', '/developers', '/embed/try-on', '/faq', '/features', '/features/[slug]', '/help', '/help/[slug]',
  '/how-it-works', '/industries', '/industries/[slug]', '/integrations', '/p/[store]/[product]', '/partners',
  '/pricing', '/privacy', '/refund', '/salla', '/terms', '/try-on-privacy', '/zid',
  // Metadata routes (app/(site)/robots.ts, sitemap.ts).
  '/robots.txt', '/sitemap.xml',
] as const;

const PATTERNS = SITE_PAGES.map((page) => new RegExp(`^${page.replace(/\[[^\]]+\]/g, '[^/]+')}$`));

/** Whether a request path is one of the website's pages. `/salla/app` is the dashboard's (T61). */
export function isSitePath(pathname: string): boolean {
  const clean = pathname.length > 1 ? pathname.replace(/\/$/, '') : pathname;
  return PATTERNS.some((pattern) => pattern.test(clean));
}
